# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20161105_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='belong_to',
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='static/images/default.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
