# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20161114_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='{% static "images/default.png"%}', max_length=100),
        ),
    ]
