# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
