# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/images/avatar_hou.png', upload_to='avatars'),
        ),
    ]
