# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0004_auto_20161118_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='你的真实姓名', max_length=50, null=True)),
                ('sex', models.CharField(choices=[('性别', '性别'), ('男', '男'), ('女', '女')], max_length=10)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='avatar_img')),
            ],
        ),
    ]
