# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0008_auto_20161118_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_img',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to='avatar_img'),
        ),
    ]
