# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0043_auto_20161119_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('dislike', 'dislike'), ('normal', 'normal'), ('like', 'like')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_img'),
        ),
    ]
