# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20161117_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar_image',
            field=models.CharField(default='/static/images/', max_length=250, null=True),
        ),
    ]
