# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20161126_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(blank=True, default=b'\xe6\x9c\xaa\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x8f\x8f\xe8\xbf\xb0', max_length=250, null=True),
        ),
    ]
