# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20161127_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(blank=True, default='未添加描述', max_length=250, null=True),
        ),
    ]
